

apiVersion: v1
data:
  username: dGVzdGFy
  password: dGVzdGFy
  connectionString: cG9zdGdyZXNxbDovL3Rlc3Q6dGVzdGFyQHBvc3RncmVzLXJ3LnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvcmVnaXN0cnk=

kind: Secret
metadata:
  name: vaultwarden-postgres

  annotations:
    replicator.v1.mittwald.de/replicate-to: "vaultwarden"

type: kubernetes.io/basic-auth



