apiVersion: batch/v1
kind: Job
metadata:
  name: registry-db-user-job # Name of the kubernetes job that creates the database
spec:
  template:
    spec:
      containers:
        - name: pg-client # Container name in kubernetes, doesn't really matter
          image: postgres:15  # Docker image to use, in the case latest postgres from docker hub, should probably have a fixed version. :latest, :14
          
          env:
            - name: PGDATABASE # This env variable is used per default, by PSQL
              value: postgres # Database name of default database, almost always "postgres" 
            - name: PGHOST # This env variable is used per default, by PSQL
              value: postgres-rw.postgres.svc.cluster.local # Database host. Easiest way to check is to check the services created by operator
            - name: PGUSER # This env variable is used per default, by PSQL
              valueFrom: 
                secretKeyRef:
                  name: superuser-secret
                  key: username
            - name: PGPASSWORD # This env variable is used per default, by PSQL
              valueFrom:
                secretKeyRef: 
                  name: superuser-secret # postgres
                  key: password
            - name: APPLICATIONUSER
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.userSecretKey }}
            - name: APPLICATIONPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.passwordSecretKey }}

          command: ["psql","-c", "CREATE ROLE $(APPLICATIONUSER) WITH LOGIN PASSWORD '$(APPLICATIONPASSWORD)'"]
      restartPolicy: Never
  backoffLimit: 10
---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-db-job
spec:
  template:
    spec:
      containers:
        - name: pg-client
          image: postgres
          env:
            - name: PGDATABASE
              value: postgres
            - name: PGHOST
              value: postgres-rw.postgres.svc.cluster.local
            - name: PGUSER
              valueFrom:
                secretKeyRef: 
                  name: superuser-secret
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: superuser-secret # postgres
                  key: password
            - name: REGISTRYUSER
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.userSecretKey }}
            - name: REGISTRYDB
              value: registry
            - name: REGISTRYPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.passwordSecretKey }}
          command: ["psql","-c", "CREATE DATABASE $(REGISTRYDB) WITH OWNER $(REGISTRYUSER)"]
      restartPolicy: Never
  backoffLimit: 10
---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-db-grant-job
spec:
  template:
    spec:
      containers:
        - name: pg-client
          image: postgres
          env:
            - name: PGDATABASE
              value: postgres
            - name: PGHOST
              value: postgres-rw.postgres.svc.cluster.local
            - name: PGUSER
              valueFrom:
                secretKeyRef: 
                  name: superuser-secret
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: superuser-secret # postgres
                  key: password
            - name: REGISTRYUSER
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.userSecretKey }}
            - name: REGISTRYDB
              value: registry
            - name: REGISTRYPASSWORD
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.vaultwarden.secretName }}
                  key: {{ .Values.vaultwarden.passwordSecretKey }}
          command: ["psql","-c", "GRANT ALL PRIVILEGES ON DATABASE $(REGISTRYDB) TO $(REGISTRYUSER)"]
      restartPolicy: Never
  backoffLimit: 10
